apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: schoolingr
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host:
    http:
      paths:
      - path: /api/trainings
        backend:
          serviceName: schoolbe
          servicePort: 8080
  - host:
    http:
      paths:
      - path: /trainings
        backend:
          serviceName: schoolfe
          servicePort: 8081
