apiVersion: v1
kind: Service
metadata:
  name: schoolbe-test
spec:
  selector:
    app: school
    tier: backend
  ports:
    - protocol: "TCP"
      nodePort: 31134
      port: 8080
      targetPort: 8080
  type: LoadBalancer
