kind: PersistentVolume
apiVersion: v1
metadata:
  name: schoolpv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/trainingappstorage"
  storageClassName: manual
