apiVersion: v1
kind: Service
metadata:
  name: schoolfe
spec:
  selector:
    app: school
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolfe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: school
        tier: frontend
        track: stable
    spec:
      containers:
        - name: schoolfectn
          image: royasoftware/trainingfrontend:v1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: TRAINING_API_LOCAL_IP
              value: schoolbe.default.svc.cluster.local
