apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: 5672
    name: port-5672
    nodePort: 30672
  - port: 4369
    name: port-4369
  - port: 5671
    name: port-5671
  - port: 15672
    name: port-15672
    nodePort: 31672
  - port: 15674
    name: port-15674
    nodePort: 31674
  - port: 25672
    name: port-25672
  type: NodePort
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: byteflair/rabbitmq-stomp
        ports:
          - containerPort: 5672
            name: port-5672
          - containerPort: 4369
            name: port-4369
          - containerPort: 5671
            name: port-5671
          - containerPort: 15672
            name: port-15672
          - containerPort: 15674
            name: port-15674
          - containerPort: 25672
            name: port-25672